name:                crisp
version:             0.1.0.0

ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Widentities
- -Wredundant-constraints

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

executables:
  crisp-exe:
    main:               Main.hs
    source-dirs:        src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crisp

library:
  source-dirs: src

tests:
  crisp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crisp
    - hspec
    - QuickCheck
    - generic-random
